export const barberConfig = {
  name: "IRON BLADE",
  tagline: "Where Legends Are Made",
  subtitle: "Premium Barbershop & Grooming Lounge",
  description:
    "Experiência premium em barbearia masculina. Cortes clássicos, barbear tradicional e cuidados exclusivos para o homem moderno.",
  phone: "(11) 98765-4321",
  whatsapp: "5511987654321",
  email: "contato@ironblade.com.br",
  address: {
    street: "Rua Augusta, 2847",
    neighborhood: "Jardins",
    city: "São Paulo",
    state: "SP",
    zipCode: "01413-100",
  },
  hours: {
    weekdays: "Segunda a Sexta: 9h às 21h",
    saturday: "Sábado: 8h às 19h",
    sunday: "Domingo: 10h às 17h",
  },
  social: {
    instagram: "https://instagram.com/ironbladebarbershop",
    facebook: "https://facebook.com/ironbladebarbershop",
    whatsapp: "https://wa.me/5511987654321",
    youtube: "https://youtube.com/@ironbladebarbershop",
  },
}

export const services = [
  {
    id: 1,
    name: "Signature Cut",
    description: "Corte personalizado com consulta de estilo e finalização premium",
    price: "R$ 65",
    duration: "60 min",
    icon: "Scissors",
    featured: true,
  },
  {
    id: 2,
    name: "Classic Shave",
    description: "Barbear tradicional com navalha, toalha quente e produtos artesanais",
    price: "R$ 45",
    duration: "45 min",
    icon: "Razor",
    featured: true,
  },
  {
    id: 3,
    name: "Beard Sculpting",
    description: "Modelagem e design de barba com produtos premium",
    price: "R$ 35",
    duration: "30 min",
    icon: "User",
    featured: false,
  },
  {
    id: 4,
    name: "The Full Experience",
    description: "Corte + Barba + Tratamento facial + Massagem relaxante",
    price: "R$ 120",
    duration: "90 min",
    icon: "Crown",
    featured: true,
  },
  {
    id: 5,
    name: "Hair Styling",
    description: "Penteado e finalização com produtos de alta performance",
    price: "R$ 25",
    duration: "20 min",
    icon: "Sparkles",
    featured: false,
  },
  {
    id: 6,
    name: "Eyebrow Design",
    description: "Design e modelagem de sobrancelhas masculinas",
    price: "R$ 20",
    duration: "15 min",
    icon: "Eye",
    featured: false,
  },
]

export const team = [
  {
    id: 1,
    name: "Marcus Steel",
    role: "Master Barber & Founder",
    experience: "15+ anos",
    specialty: "Cortes clássicos e barbear tradicional",
    image: "/placeholder.svg?height=400&width=400",
    instagram: "@marcussteel_barber",
  },
  {
    id: 2,
    name: "Diego Razor",
    role: "Senior Barber",
    experience: "8+ anos",
    specialty: "Fades modernos e design de barba",
    image: "/placeholder.svg?height=400&width=400",
    instagram: "@diegorazor_cuts",
  },
  {
    id: 3,
    name: "Bruno Edge",
    role: "Style Specialist",
    experience: "6+ anos",
    specialty: "Cortes modernos e styling",
    image: "/placeholder.svg?height=400&width=400",
    instagram: "@brunoedge_style",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Rafael Mendes",
    role: "CEO Tech Startup",
    text: "Melhor barbearia de SP! Atendimento VIP e resultado sempre perfeito. Virei cliente fiel.",
    rating: 5,
    avatar: "RM",
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 2,
    name: "Carlos Oliveira",
    role: "Advogado",
    text: "Ambiente incrível, profissionais top e aquele cafezinho especial. Recomendo demais!",
    rating: 5,
    avatar: "CO",
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 3,
    name: "André Silva",
    role: "Empresário",
    text: "Tradição e modernidade em perfeita harmonia. Cada visita é uma experiência única.",
    rating: 5,
    avatar: "AS",
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 4,
    name: "Pedro Santos",
    role: "Influencer",
    text: "Barbeiros artistas! Sempre saio de lá com um visual incrível. Vale cada centavo.",
    rating: 5,
    avatar: "PS",
    image: "/placeholder.svg?height=100&width=100",
  },
]
